name: Ubuntu armv7 (GCC 11)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Test
        id: runcmd
        with:
          arch: armv7
          githubToken: ${{ github.token }}
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -y cmake make g++
          run: |
            cmake -B build
            cmake --build build -j=2
            ctest --output-on-failure --test-dir build
            cmake -DCMAKE_CXX_FLAGS="-fstack-protector-strong -fno-strict-aliasing" -B buildprotected
            cmake --build buildprotected -j=2
            ctest --output-on-failure --test-dir buildprotected